import "reflect-metadata";
import express, { RequestHandler } from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import helmet from "helmet";
import morgan from "morgan";
import rateLimit from "express-rate-limit";
import { env } from "./config/env";
import { errorHandler, notFound } from "./utils/http";
import authRoutes from "./modules/auth/routes";
import clientRoutes from "./modules/clients/routes";
import settingsRoutes from "./modules/settings/routes";
import proposalRoutes from "./modules/proposals/routes";
import publicProposalRoutes from "./modules/public-proposals/routes";
import paymentRoutes, { proposalPaymentRouter, publicPaymentRouter } from "./modules/payment-requests/routes";
import fileRoutes, { publicFileRouter } from "./modules/files/routes";
import dashboardRoutes from "./modules/dashboard/routes";

export const createApp = () => {
  const app = express();
  app.use(helmet({ crossOriginResourcePolicy: { policy: "cross-origin" } }));
  app.use(cors({ origin: env.CORS_ORIGIN.split(","), credentials: true }));
  app.use(express.json({ limit: "1mb" }));
  app.use(cookieParser() as unknown as RequestHandler);
  app.use(morgan(env.NODE_ENV === "production" ? "combined" : "dev"));
  const sensitiveLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 100, standardHeaders: "draft-7", legacyHeaders: false });
  app.get("/api/v1/health", (_req, res) => res.json({ success: true, data: { status: "ok" } }));
  app.use("/api/v1/auth", sensitiveLimiter as unknown as RequestHandler, authRoutes);
  app.use("/api/v1/clients", clientRoutes);
  app.use("/api/v1/settings", settingsRoutes);
  app.use("/api/v1/proposals", proposalRoutes);
  app.use("/api/v1/proposals", proposalPaymentRouter);
  app.use("/api/v1/public/proposals", sensitiveLimiter as unknown as RequestHandler, publicProposalRoutes);
  app.use("/api/v1/payment-requests", paymentRoutes);
  app.use("/api/v1/public/payment", sensitiveLimiter as unknown as RequestHandler, publicPaymentRouter);
  app.use("/api/v1/public/payment", sensitiveLimiter as unknown as RequestHandler, publicFileRouter);
  app.use("/api/v1/files", sensitiveLimiter as unknown as RequestHandler, fileRoutes);
  app.use("/api/v1/dashboard", dashboardRoutes);
  app.use(notFound);
  app.use(errorHandler);
  return app;
};
